### PR TITLE
Be more pythonic

### PR DESCRIPTION
**Pull request by Chilipp**
Hey @Try2Code! I was always a bit disappointed by how the cdo-bindings handle the chaining of operators. This chain is one of the greatest features of CDOs and the current implementation

```python
cdo.operatort(input='-op1 -op2 infile1 infile2')
```

is not very pythonic, in that sense, that it requires long string manipulations. But CDOs are written in an object-oriented manner and so should the python bindings! 

With this PR, I propose a new method (although backwards-compatibility of the API is assured!). Instead of chaining the operators as a string, you chain them as python objects:

```python
cdo.operator.op1.op2.infile(infile1, infile2).read()
```

This has multiple advantage compared the the old approach:

1. it much better mimics the OO-shell approach of CDOs
2. it makes your operators reusable

  ```python
  chain = cdo.output.fldmean
  v1 = chain.selname('t2m').infile('demo.nc').read()
  v2 = chain.selname('u').infile('demo.nc').read()
  ```
3. it makes the help better accessible:
  ```python
  help(cdo.output.fldmean) # prints the help of fldmeann
  ```

You can play around a bit interactively with [this gist](https://gist.github.com/Chilipp/5c3f2e5151ce047bac3a0f33c1446304) on binder by clicking on the following button: [Binder](https://mybinder.org/v2/gist/Chilipp/5c3f2e5151ce047bac3a0f33c1446304/master)

## Changes to the code
As I said previously, the old API is still preserved, so it is backwards compatible. However, I changed some of the internals:

1. The `Cdo` class can now be used as a descriptor (i.e. I implemented a `Cdo.__get__` method). Accessing such a descriptor returns a new instance of the `Cdo` class with the same properties but an enhanced cdo command (`cmd`)
2. instances of the `Cdo` are callable (i.e. they have a `__call__` method). This method essentially has the same content as methods that have been formerly defined in the `Cdo.__getattr__` method
3. The `__getattr__` method now does not add new methods to the `Cdo` class anymore. Instead it subclases the `Cdo` class and adds the new instance as an attributes to the `Cdo` class. With the two previous implementations (the `__get__` and `__call__` methods), they API is still the same. Only the attribute types changed:
  
  - previous:
    ```python
    type(cdo.output)
    # method
    ```
  - new:
    ```python
    type(cdo.output)
    # cdo.Cdo.__getattr__.<locals>.Operator
    isinstance(cdo.output, Cdo)
    # True
    ```
4. I implemented an `infile` method and a `read` method. Note that
  ```python
  cdo.fldmean.infile('demo.nc').read('output.nc')
  ```
  gives the same result as
  ```python
  cdo.output(input='demo.nc', output='output.nc')
  ```
5. the `ifile` for the `readXArray`, etc. methods is now optional. If not provided, the `read` method is called and the data is calculated
6. I also added two more tests: the `test_pychain` and `test_pychain2` methods.

### CODE REVIEW

**Comment by Chilipp** [comment]
Well, ok, there are a few backwards incompatible changes. I assume that, if one calls `cdo.operator('arg')` that he does not want to compute anything but only appends an argument to
the operator chain. So 
```python
cdo.operator('arg')
``` 
does not start the subprocess, but 
```python
cdo.operator('arg', input='demo.nc')
```` 
does. This causes problems for the very few operators that do not need any infiles, such as `topo`. Hence, to retain the behaviour of 
```python
cdo.topo('r100x100')
```
one has now to use
```python
cdo.topo('r100x100', compute=True)
# or
cdo.topo('r100x100').read()
```

**Comment by Try2Code** [comment]
hi @Chilipp !

Thx for the effort - this is an interesting approach. The is a chaining-addon for CDO (https://github.com/ucyo/xsuite -> xcdo). I wasn't really happy with it and I wanted to keep the interface simple. so I decided to not integrate it. this was more than a year ago and meanwhile I was wondering if this was a good or bad decision several times - still I am not sure. 
No doubt the chaining is attractive *and* the string processing of more complex chains is awkward. But on the other hand I want to keep the automatic generation of tempfiles as the normal return type.

Next point are operators with multiple output files - I wrote a test for this, so this seems to work - but I will check your code in detail.

I am not really happy with my implementation of ```__getattr__```. it's too long and hard to read. Please give me some time to analyze your code and get familiar with the implications.

**Comment by Chilipp** [comment]
Sure, this is just a proposal of adding new functionalities to this package without leveraging it's complexity too much. 

> Please give me some time to analyze your code and get familiar with the implications.

Take your time, I do not have any pressure on this 😄

**Comment by Try2Code** [comment]
As an extreme example I tried to re-write a very long chain tests: https://github.com/Try2Code/cdo-bindings/blob/master/python/test/test_cdo.py#L793

It's was not possible due to a syntax error. At first I didn't understand. But then I wrote a little test with 
```python
cdo.timsum.for(1,10)
```
The problem is  the ```for``` operator.  It is interpreted as a keyword - in both implementations. I have to admit that I never noticed that. ```for``` is not used very often I think, because you cen only generate data with it. In my implementation  I can hide this by using something like
```python
cdo.copy(input='-for,1,10')
```
But in your implementation is not possible, because it has to be called explicitly. The only solution I can think of is renaming ```for``` to ```seq``` in CDO. I will talk with Uwe about it. For now we could rename it within the python interface

**Comment by Chilipp** [comment]
Hmm, that sounds like a good way. There is, however, also another possibility. I could also implement to access operators through the `__getitem__` method. 
This would provide a safe way to access any operator and it is straight forward to be implemented. In this way, you could access this operator via `cdo['for']`.

Another possibility, that already works now, is to use pythons `getattr` function:
```python
getattr(cdo.timsum, 'for')(1, 10)
```

**Comment by Try2Code** [comment]
I added a couple of lines for the aliasing

**Comment by Chilipp** [comment]
all right, looks good. tell me when you want me to implement them in this PR

**Comment by Chilipp** [comment]
> I added a couple of lines for the aliasing

all right @Try2Code, I merged this *aliasing* and your new test into this PR (https://github.com/Try2Code/cdo-bindings/pull/22/commits/dcf7b7d8f838d9c74458f0f25bbbf0bf3f8054f6)

**Comment by Try2Code** [comment]
I asked Uwe about renaming ```for``` to ```seq``` and he is ok with it. So I will document this _for_-problem here as a known issue and that's it.

**Comment by Chilipp** [comment]
All right. Does this mean, that I should revert the `AliasOperator` commit?

**Comment by Try2Code** [comment]
No, unfortunately not. cdo.py has to run with all kinds of CDO releases, so I have to handle several of these special cases (https://github.com/Try2Code/cdo-bindings/blob/master/python/cdo.py#L191, https://github.com/Try2Code/cdo-bindings/blob/master/python/cdo.py#L209, https://github.com/Try2Code/cdo-bindings/blob/master/python/cdo.py#L179)

The ```for``` operators will be turned into ```seq``` in the next release, but for all older versions the code is needed. 

btw I'd like to replace ```read()``` with ```run()``` ;-)

**Comment by Chilipp** [comment]
Hey @Try2Code! I renamed the method now (see https://github.com/Try2Code/cdo-bindings/pull/22/commits/e3f83a02c43d3d55990057ad6b8958592b1b0b26, sorry, I forgot about this). I think, we should decide whether this PR should then be merged or rejected because it always requires to merge the upstream branch manually into this PR branch if you do any changes. If you say, you would like to merge this PR, I will resolve the merge conflicts

**Comment by Try2Code** [comment]
hi @Chilipp !
Sorry for not responding sooner - had some other trouble so solve. On top of that cdo-1.9.7 was released yesterday, so I had to put a workaround into cdo-bindings to support the renaming of ```for -> seq```. This is good for us, but requires some extra work on the other hand. But the main reasons are these:
* I need to understand your implementation. Honestly I wasn't happy with my one from the start. The extra need of knowledge how to put an operator chain in the ```input``` argument somehow breaks the beauty of it. But I wanted to keep it simple (esp. for me ;-)) on one side and didn't have the knowledge to do it in a smart way on the other side. Another developer came up with a similar interface years ago, but I wasn't really happy with the implementation at that time.
* My plan was and is to keep both the ruby and python implementation inline with each other. Hence i have to think about how to do this in ruby - another reason to spend some more time in understanding your work.
* More a concern then a reasoning _against_ your changes: I consider this as a major change in the interface - this is worth a 2.0 version of the package. It will break other ppl's scripts in case they just update from 1.5. At the end this will not keep me from developing, because if it did, it would mean to limit the possibilities significantly.

Finally - **yes**, I'd like to have your changes incorporated! I can postpone the release of a proper ruby-implementation and gain some more experience with yours - even after a merge. I just wanted to point out that I have to take some time to fully understand it - otherwise I couldn't be the maintainer of it anymore.
My suggestion: I will fix the current issues with the CI testing and some problems I have running them locally on my machine with cdo-1.9.7. This will be done not later than this Friday. Then I will stop pushing stuff to master and would like you to update with the upstream one final time and  make the tests run. After that I will directly merge your PR. Sound's like a plan?

**Comment by Chilipp** [comment]
Thanks for the detailed explanation! Sounds great 😄

> I consider this as a major change in the interface

Yes, indeed it is, so please be critical about this contribution. But note, that backwards compatibility is ensured because the `input` keywords, etc. still works as it worked before. Only commands that require no input at all (e.g. something like `cdo.topo('r10x10')`) would be affected.

**Comment by Try2Code** [comment]
I finished the issue with the testing systems. It's now running in about 4 mins instead of 12. you can now start to update your branch with cdo-binding/master

cheers

**Comment by Chilipp** [comment]
All right, thanks :)! 
I merged the upstream branch and locally every test passed. So from my perspective you can merge this when the CI finished!

**Comment by Try2Code** [comment]
all test are running fine now. I will rethink how to return different types of results, e.g. numpy, xarray,cdf-handles - there the interface doesn't work:
```
value = cdo.vertsum(returnArray='T').stdatm(0,12,123,1234).run()
```
But the _run_-methods seems to be good candidate for such final output setups.

Anyway - I see this as a very  **BIG** step forward - Cannot thank you enough for this @Chilipp :bowing_man:

**Comment by Chilipp** [comment]
You're very welcomed :smile: Thanks to you for your efforts in providing nice CDO bindings for python!

Yes, as soon as you provide any keywork to the operator call (`vertsum()`), it will do the calculation. This was necessary to ensure backwards compatibility.
Hence, in the setting where you set something like `returnArray='T'`, it will give you a numpy array (as it was before):

```python
type(cdo.vertsum(returnArray='T'))
numpy.ndarray
```
 and this does then not have a `stdatm` attribute. Therefore

```python
cdo.vertsum(returnArray='T').stdatm(0, 12, 123, 1234)
```

has to fail. 

What instead works, would be to put that at the end, e.g. via

```python
cdo.vertsum().stdatm(0,12,123,1234).readArray(varname='T')
# or 
cdo.vertsum().stdatm(0,12,123,1234, returnArray='T')
```

I also did implement something to avoid the computation by setting `compute=False` in the call: If you type
```python
cdo.vertsum(returnArray='T', compute=False)
```
you will get a CDO operator, and as such
 
```python
cdo.vertsum(returnArray='T', compute=False).stdatm(0,12,123,1234).run()
```
will work. However, the `returnArray` is then ignored completely and you get the path to the temporary file, so it does not help you at all.

**Pull request merged**
