### PR TITLE
Enforce pep8 compatibility

### PR DESCRIPTION
**Pull request by lukelbd**
This enforces [pep8 compatibility](https://peps.python.org/pep-0008/) throughout the `cdo.py` binding. Not exactly critical but could help encourage contributions if this package sticks to a standard format (thanks for making it, I find this package extremely useful!).

I used the [autopep8 tool](https://pypi.org/project/autopep8/) to start, which mostly just increased the indentaiton to 4 spaces, then added a few line breaks and changed instances of `x == None`, `x != None`, `x != True` to `x is None`, `x is not None`, `x is not True`.

This didn't take long -- and just noticed you have a couple active pull requests. So, if this messes them up too much / it's too hard to rebase, I'd be happy to close this PR and resubmit later when it's easier to merge.

### CODE REVIEW

**Comment by lukelbd** [comment]
Also might want to delete the `# {{{` and `# }}}` vim folding indicators since these days there are [vim plugins](https://github.com/tmhedberg/SimpylFold) that provide folding that recognize python structures, but not a huge deal.

**Comment by Try2Code** [comment]
> Also might want to delete the `# {{{` and `# }}}` vim folding indicators since these days there are [vim plugins](https://github.com/tmhedberg/SimpylFold) that provide folding that recognize python structures, but not a huge deal.

I cannot find something in  pep8 regarding technical comments like '# {{{' . For sure it has nothing to do with the code itself, but the same is true for the modeline at the end of the file.

**Comment by lukelbd** [comment]
Thanks for merging! Yep you're right folding indicators are totally compatible, was being too picky

**Comment by Try2Code** [comment]
all cool - thx for the initiative. this part of coding is always at the edge: personal style which cat get into the way of other possible coders. I simple wasn't aware of the pep8 standard. Never looked for something like it tbh. 

I prefer 2 space for indent because I usually work in the terminal, which is somewhat old-school - totally admit that.

**Comment by lukelbd** [comment]
Fair, yeah this personal style stuff is tricky (have to weigh benefits to collaborators against personal disagreement and time sink of reformatting -- luckily autoformatters like `autopep8` help).

For a completely dictatorial take you should see the [black project](https://github.com/psf/black) -- a ruthlessly strict subset of pep8. Was initially anguished about it due to my own coding preferences but slowly starting to use it.

**Pull request merged**
